repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=2048]

  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: hatch fmt
        language: python
        types: [python]
        pass_filenames: false
        verbose: true
      - id: cov
        name: cov
        entry: hatch run cov
        language: python
        types: [python]
        pass_filenames: false
