#################################
#     Advent of Code Tests      #
#         Year: 2016            #
#           Day: 18             #
#################################
[test.test_01]
part = 1
input = """ABCDE
12345"""
answer = 38
