#################################
#     Advent of Code Tests      #
#         Year: 2016            #
#           Day: 20             #
#################################
[test.test_01]
part = 1
input = """5-8
0-2
4-7"""
args=[0, 9]
answer = 3

[test.test_02]
part = 2
input = """5-8
0-2
4-7"""
args=[0, 9]
answer = 2
