#################################
#     Advent of Code Tests      #
#         Year: 2016            #
#           Day: 16             #
#################################
[test.test_01]
part = 1
input = "10000"
args = [20]
answer = "01100"
